# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
locale: es
title: Cristian Baeza Torres
email: crisbaezatorres@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hola! Soy Cristian Baeza T, Antropólogo con mención Física UdeC.
  Concepción, Chile. 
twitter_username: CrisBaeza_13
github_username: CBaezaT
minimal_mistakes_skin: "contrast"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Cristian Baeza"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Hola, soy Cristian Baeza Torres, Antropólogo con Mención Física de la Universidad de Concepción.
  Concepción, Chile."
  links:
   # - label: "Website"
    #  icon: "fas fa-fw fa-link"
   #   url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/CrisBaeza_13"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CBaezaT"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/crisbaeza13/"
    - label:  "Linkedin"
      icon: "fab fa-fa fa-linkedin"
      url: "https://www.linkedin.com/in/cristian-baeza-torres-a56160161/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/CBaezaT"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/crisbaeza13/"
    - label:  "Linkedin"
      icon: "fab fa-fa fa-linkedin"
      url: "https://www.linkedin.com/in/cristian-baeza-torres-a56160161/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: wide
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: wide
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

